trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  targetRuntime: 'win-x64'

steps:
  # Nastavení prostředí .NET
  - task: UseDotNet@2
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  # Build API projektu
  - task: DotNetCoreCLI@2
    displayName: 'Build .NET Project for API'
    inputs:
      command: 'build'
      projects: './Forms.Api.App/Forms.Api.App.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Publish API projektu
  - task: DotNetCoreCLI@2
    displayName: 'Publish .NET Project for API'
    inputs:
      command: 'publish'
      projects: './Forms.Api.App/Forms.Api.App.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api-app'
      zipAfterPublish: true

  # Build IdentityProvider projektu
  - task: DotNetCoreCLI@2
    displayName: 'Build .NET Project for IdentityProvider'
    inputs:
      command: 'build'
      projects: './Forms.IdentityProvider.App/Forms.IdentityProvider.App.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Publish IdentityProvider projektu
  - task: DotNetCoreCLI@2
    displayName: 'Publish .NET Project for IdentityProvider'
    inputs:
      command: 'publish'
      projects: './Forms.IdentityProvider.App/Forms.IdentityProvider.App.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/identity-provider'
      zipAfterPublish: true

  # Build Web projektu
  - task: DotNetCoreCLI@2
    displayName: 'Build .NET Project for Web App'
    inputs:
      command: 'build'
      projects: './Web/Forms.Web.App/Forms.Web.App.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Publish Web projektu
  - task: DotNetCoreCLI@2
    displayName: 'Publish .NET Project for Web App'
    inputs:
      command: 'publish'
      projects: './Web/Forms.Web.App/Forms.Web.App.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/web-app'
      zipAfterPublish: true

  # Uložení artefaktů (API)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish API Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/api-app'
      ArtifactName: 'api-app-artifact'
      publishLocation: 'Container'

  # Uložení artefaktů (IdentityProvider)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish IdentityProvider Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/identity-provider'
      ArtifactName: 'identity-provider-artifact'
      publishLocation: 'Container'

  # Uložení artefaktů (Web)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Web Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/web-app'
      ArtifactName: 'web-app-artifact'
      publishLocation: 'Container'

  # Nasazení na Azure Web App (API)
  - task: AzureWebApp@1
    displayName: 'Deploy API to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-api'
      package: '$(Build.ArtifactStagingDirectory)/api-app/**/*.zip'

  # Nasazení na Azure Web App (IdentityProvider)
  - task: AzureWebApp@1
    displayName: 'Deploy IdentityProvider to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-identity'
      package: '$(Build.ArtifactStagingDirectory)/identity-provider/**/*.zip'

  # Nasazení na Azure Web App (Web)
  - task: AzureWebApp@1
    displayName: 'Deploy Web App to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-web'
      package: '$(Build.ArtifactStagingDirectory)/web-app/**/*.zip'
