trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  targetRuntime: 'win-x64'

steps:
  # Nastavení prostředí .NET
  - task: UseDotNet@2
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  # Build API projektu
  - script: |
      dotnet build ./Forms.Api.App/Forms.Api.App.csproj --configuration $(buildConfiguration)
    displayName: 'Build .NET Project for API'

  # Publish API projektu
  - script: |
      dotnet publish ./Forms.Api.App/Forms.Api.App.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api-app --no-dependencies
    displayName: 'Publish .NET Project for API'

  # Zabalování výstupu do ZIP souboru
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/api-app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/api-app.zip'
      replaceExistingArchive: true

  # Nasazení na Azure Web App
  - task: AzureWebApp@1
    displayName: 'Deploy API to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-api'
      package: '$(Build.ArtifactStagingDirectory)/api-app.zip'

 # Build Web projektu
  - task: DotNetCoreCLI@2
    displayName: 'Build .NET Project for Web App'
    inputs:
      command: 'build'
      projects: './Web/Forms.Web.App/Forms.Web.App.csproj'
      arguments: '--configuration $(buildConfiguration)'

  # Publish Web projektu
  - task: DotNetCoreCLI@2
    displayName: 'Publish .NET Project for Web App'
    inputs:
      command: 'publish'
      projects: './Web/Forms.Web.App/Forms.Web.App.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/web-app'
      zipAfterPublish: true

  # Uložení artefaktů (Web)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Web Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/web-app'
      ArtifactName: 'web-app-artifact'
      publishLocation: 'Container'

  # Nasazení Web App na Azure App Service
  - task: AzureWebApp@1
    displayName: 'Deploy Web App to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-web'
      package: '$(Build.ArtifactStagingDirectory)/web-app/**/*.zip'