trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  targetRuntime: 'win-x64'

steps:
  # Nastavení prostředí .NET
  - task: UseDotNet@2
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  # Build API projektu
  - script: |
      dotnet build ./Forms.Api.App/Forms.Api.App.csproj --configuration $(buildConfiguration)
    displayName: 'Build .NET Project for API'

  # Publish API projektu
  - script: |
      dotnet publish ./Forms.Api.App/Forms.Api.App.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api-app --no-dependencies
    displayName: 'Publish .NET Project for API'

  # Zabalování výstupu do ZIP souboru
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/api-app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/api-app.zip'
      replaceExistingArchive: true

  # Nasazení na Azure Web App
  - task: AzureWebApp@1
    displayName: 'Deploy API to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-api'
      package: '$(Build.ArtifactStagingDirectory)/api-app.zip'

#######################

   # Build WEB projektu
  - script: |
      dotnet build ./Web/Forms.Web.App/Forms.Web.App.csproj --configuration $(buildConfiguration)
    displayName: 'Build .NET Project for WEB'

  # Publish WEB projektu
  - script: |
      dotnet publish ./Web/Forms.Web.App/Forms.Web.App.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/web-app --no-dependencies
    displayName: 'Publish .NET Project for WEB'

  # Zabalování výstupu do ZIP souboru
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/web-app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/web-app.zip'
      replaceExistingArchive: true

  # Nasazení na Azure Web App
  - task: AzureWebApp@1
    displayName: 'Deploy WEB to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-web'
      package: '$(Build.ArtifactStagingDirectory)/web-app.zip'
      

######################################

   # Build Identity projektu
  - script: |
      dotnet build ./Forms.IdentityProvider.App/Forms.IdentityProvider.App.csproj --configuration $(buildConfiguration)
    displayName: 'Build .NET Project for Identity'

  # Publish Identity projektu
  - script: |
      dotnet publish ./Forms.IdentityProvider.App/Forms.IdentityProvider.App.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/identity-app --no-dependencies
    displayName: 'Publish .NET Project for Identity'

  # Zabalování výstupu do ZIP souboru
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/identity-app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/identity-app.zip'
      replaceExistingArchive: true

  # Nasazení na Azure Identity App
  - task: AzureWebApp@1
    displayName: 'Deploy identity to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-identity'
      package: '$(Build.ArtifactStagingDirectory)/identity-app.zip'