trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  dotNetFramework: 'net8.0'
  dotNetVersion: '8.0.x'
  targetRuntime: 'win-x64'

steps:
  - task: UseDotNet@2
    inputs:
      version: $(dotNetVersion)
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Build .NET Project'
    inputs:
      command: 'build'
      projects: '**/Forms.Api.App.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish .NET Project'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'AzureConnectionToAppService'
      appType: 'webApp'
      appName: 'app-iw5-2024-team-xdolak09-api'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
